services:
  closet-album:
    image: ghcr.io/kimo2411/libre-closet:latest
    container_name: closet-album
    ports:
      - "32180:3000"
    environment:
      APP_NAME: 家庭衣物相册
      AUTH_ENABLED: "false"
      DISABLE_REGISTRATION: "true"
      PWA_ENABLED: "false"
      DATA_PATH: /app/data
      DATABASE_TYPE: sqlite
      FILE_STORAGE_TYPE: local
    volumes:
      - ./data:/app/data
    restart: unless-stopped
